apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      type: Deployment
      env: Deployment
  template:
    metadata:
      labels:
          type: Deployment
          env: Deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          env:
            - name : APP_ENV
              valueFrom: 
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name : DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
     type: Deployment
     env: Deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  